services:
  database:
    build: .
    container_name: database_dev
    ports:
      - "5432:5432"
    env_file:
      - .env

    volumes:
      - ./postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
